### ISSUE TITLE
Problem with `tweet_id`

### ISSUE THREAD

**Issue by adrdangelo** [vosonlab/voson.tcn#1]
Hello, 
I have tried to use 
`tcn_threads("https://twitter.com/ChristianDalPo1/status/1381413221916106756", token)`
but I  received this error message: 
`"Erro: Join columns must be present in data.
x Problem with tweet_id."`

My code:
```R
# library(rtweet)
# library(dplyr)

# api_key <- "XXXXXX"
# api_secret <- "XXXXXX"

# token <- tcn_token(consumer_key = api_key, consumer_secret = api_secret)
# tweets <- tcn_threads("https://twitter.com/ChristianDalPo1/status/1381413221916106756", token)
```
and exploring the `last_error()`, I've notice this:
```
<error/rlang_error>
Join columns must be present in data.
x Problem with `tweet_id`.
Backtrace:
 1. voson.tcn::tcn_threads(...)
 2. voson.tcn:::get_thread(...)
 4. dplyr:::anti_join.data.frame(tweets_incl, tweets, by = c(tweet_id = "tweet_id"))
 5. dplyr:::join_filter(x, y, by = by, type = "anti", na_matches = na_matches)
 6. dplyr:::join_cols(tbl_vars(x), tbl_vars(y), by = by)
 7. dplyr:::standardise_join_by(by, x_names = x_names, y_names = y_names)
 8. dplyr:::check_join_vars(by$x, x_names)
```
And the `last_trace()`
```
x
 1. \-voson.tcn::tcn_threads(...)
 2.   \-voson.tcn:::get_thread(...)
 3.     +-dplyr::anti_join(tweets_incl, tweets, by = c(tweet_id = "tweet_id"))
 4.     \-dplyr:::anti_join.data.frame(tweets_incl, tweets, by = c(tweet_id = "tweet_id"))
 5.       \-dplyr:::join_filter(x, y, by = by, type = "anti", na_matches = na_matches)
 6.         \-dplyr:::join_cols(tbl_vars(x), tbl_vars(y), by = by)
 7.           \-dplyr:::standardise_join_by(by, x_names = x_names, y_names = y_names)
 8.             \-dplyr:::check_join_vars(by$x, x_names)
```
the same occours with the exemple:
```R
tcn_threads("https://twitter.com/AnnastaciaMP/status/1376311897624956929", token)
```

```
version.string R version 4.0.0
[1] voson.tcn_0.1.6.9000
rtweet_0.7.0  
dplyr_1.0.5 
```
that's it .
best!

**Comment by bryn-g** [comment]
Hi @adrdangelo, thanks for letting me know about this issue. I believe the error was occurring because in the case of the `https://twitter.com/ChristianDalPo1/status/1381413221916106756` tweet there are no replies, so there is no threaded conversation on which to collect tweets. I've fixed the error and added a warning message when no tweets are returned. I think I will further resolve this issue in the future by returning a single tweet and metadata.

Similarly, with the example tweet `https://twitter.com/AnnastaciaMP/status/1376311897624956929` I believe the conversation tweets are now older than 7 days and are no longer returned with an API recent search. If you have access to academic track projects and a full history search you can try using the `end_point` parameter of `tcn_threads`.

```R
tcn_threads("https://twitter.com/AnnastaciaMP/status/1376311897624956929", token, end_point = "all")
```

If you install the latest update of the package you should see the new warning message instead of an error.

```
Warning message:
no conversation tweets were collected for tweet id: 1376311897624956929.
* check conversation is threaded and that tweets are not older than 7 days.
```

Thanks again, I hope this helps.
